In [3]:
import numpy as np

In [ ]:
np.__version__

In [5]:
np.arange(0, 20, 4)

array([ 0,  4,  8, 12, 16])

In [7]:
np.square(np.arange(0, 20, 4))

array([  0,  16,  64, 144, 256])

In [4]:
np.sqrt(np.arange(0, 20, 4))

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ])

In [ ]:
# equal pieces
np.linspace(0, 20, 4)

In [ ]:
np.linspace(0, 20, 5)

In [ ]:
np.linspace(0, 20, 9)

In [48]:
np.random.seed(101) #to get the same result everytime
np.random.rand(3)

array([0.51639863, 0.57066759, 0.02847423])

In [51]:
np.zeros(6, dtype = int)

array([0, 0, 0, 0, 0, 0])

In [53]:
np.zeros(5, dtype = float)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [55]:
np.ones(3)

array([1., 1., 1.])

# Array attributes and methods such as:

In [58]:
arr = np.ones(3)

arr.shape

(3,)

In [60]:
arr.reshape(1, 3).shape

(1, 3)

In [86]:
np.random.seed(101)
ran_arr = np.random.randint(0, 50, 10)
ran_arr

array([31, 11, 17,  6, 23, 11, 47,  9, 13, 40])

In [87]:
ran_arr.max()

47

In [88]:
ran_arr.min()

6

In [89]:
ran_arr.argmax()

6

In [90]:
ran_arr.argmin()

3

In [96]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [92]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [135]:
np.random.randint(1,10,2)

array([3, 4])